-- CREATE TABLE `payment` (
--                            `id` bigint NOT NULL AUTO_INCREMENT,
--                            `amount` double DEFAULT NULL,
--                            `customer` varchar(255) DEFAULT NULL,
--                            `status` int DEFAULT NULL,
--                            `currency` int DEFAULT NULL,
--                            `type` int DEFAULT NULL,
--                            PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;